name: Create cherry-pick PR
on:
  pull_request_target:
    branches:
      - 'next'
      - 'v*.x'
      - 'master'
    types: ['closed']

permissions: {}

jobs:
  create_pr:
    name: Create cherry-pick PR
    uses: mui/mui-public/.github/workflows/prs_create-cherry-pick-pr.yml@6900bd9859fc11bbeb9ce055e8440b66147a0567
    permissions:
      contents: write
      pull-requests: write
